<template>
  <div class="home">
    <h1 class="text-center mb-5">Home Page</h1>
    <article v-for="article in articles">
      <h3 class="fw-bold">{{ article.title }}</h3>
      <div>{{ article.description }}</div>
      <a :href="`article/${article.slug}`">More ...</a>
      <hr/>
    </article>
  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'HomeView',
  data() {
    return {
      articles: [
        {
          title: "Title 1",
          slug: "title-1",
          description: "<<<<<<<<<<<< DESCRIPTION >>>>>>>>>>>>>",
          content: "<<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> "
        },
        {
          title: "Title 2",
          slug: "title-2",
          description: "<<<<<<<<<<<< DESCRIPTION >>>>>>>>>>>>>",
          content: "<<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> "
        },
        {
          title: "Title 3",
          slug: "title-3",
          description: "<<<<<<<<<<<< DESCRIPTION >>>>>>>>>>>>>",
          content: "<<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> "
        },
        {
          title: "Title 4",
          slug: "title-4",
          description: "<<<<<<<<<<<< DESCRIPTION >>>>>>>>>>>>>",
          content: "<<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> "
        },
        {
          title: "Title 5",
          slug: "title-5",
          description: "<<<<<<<<<<<< DESCRIPTION >>>>>>>>>>>>>",
          content: "<<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> <<< CONTENT>>> "
        },
      ]
    }
  }
}
</script>
